version: "3.5"

services:
    notifier-tbot-service:
        container_name: notifier-tbot-service
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - db_vol:/db
        environment:
            - TELOXIDE_TOKEN=
            - BMS_APP_VERSION=9.8.0
        restart: always
volumes:
    db_vol:
